version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  public-inbox-httpd:
    build: public-inbox
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - /root/caml-list.git:/root/caml-list.git:rw
    environment:
      - VIRTUAL_HOST=inbox.ocaml.org
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=inbox.ocaml.org
      - LETSENCRYPT_EMAIL=n.oje.bar@gmail.com
    command: public-inbox-httpd

volumes:
  certs:
  vhost:
  html:
