version: '2'
services:
  public-inbox-httpd:
    build: public-inbox
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./caml-list.git:/root/caml-list.git:ro
    command: public-inbox-httpd

  public-inbox-mda:
    build: public-inbox
    restart: always
    expose:
      - 25
    ports:
      - "25:25"
    volumes:
      - ./caml-list.git:/root/caml-list.git:rw
    command: postfix start-fg
